### PR TITLE
add theme color ogp tag

### PR DESCRIPTION
**Pull request by bnidevs**

### CODE REVIEW

**Review by Alfriadox — COMMENTED** [review]
This looks good, but does not fit with our current dynamic OGP tag system. Do we want theme color to be specifically static, or at least until it gets refactorred to be dynamic?

**Comment by bnidevs** [comment]
do .hbs files not allow for a combination of static and dynamic content?

**Comment by Alfriadox** [comment]
No they do, I'm just saying that this breaks the pattern established by the other ogp tags being dynamic, and there should be a comment/justification on why that's the case with this one.

**Comment by bnidevs** [comment]
This meta tag strictly modifies the color theme of the blocks that are displayed on Discord/elsewhere, and I assumed it could be consistent across all usages of Telescope, unless you want varying colors based on link type?

Screen Shot 2022-01-23 at 8 49 27 PM

**Comment by Alfriadox** [comment]
It might be nice to make any telescope link that errors our red, in theory. Although, after further consideration, that would be a bunch of work and a single color across-the-board is probably fine for now. This gets my approval

**Review by Alfriadox — APPROVED** [review]

**Pull request merged**
