### PR TITLE
Add #247 to changelog

### PR DESCRIPTION
**Pull request by Alfriadox**

### CODE REVIEW

**Review by bepvte — APPROVED** [review]

**Comment by Alfriadox** [comment]
@bepvte do you have perms to merge this or should I upgrade your permissions?

**Comment by bepvte** [comment]
I do not have permission to merge it.

**Comment by Alfriadox** [comment]
I sent you an invite to the @rcos/infrastructure team. Hope that fixes it

**Comment by bepvte** [comment]
I still get "The base branch restricts merging to authorized users", unfortunately

**Comment by Alfriadox** [comment]
It should be fixed now! Forgot that there was a branch protection rule on this one

**Pull request merged**
